"""
Lab 5 - Small synthetic in-domain training corpus for the deep-learning models
that are trained FROM SCRATCH (RNN, LSTM, Seq2Seq, self-attention, Transformer).

Neural summarisers cannot learn anything from a single document, so we generate
student-feedback paragraphs about the same five aspects found in a university
feedback report. For every paragraph we know

  * which sentence is the KEY sentence     -> label for extractive models
  * a short human-style abstractive summary -> target for abstractive models

A document = 3-5 paragraphs (one per aspect), each paragraph = key sentence +
2-4 supporting details (+ optional filler), key sentence usually (not always) first.
The test report in data/student_feedback.txt is NOT generated by this script.
"""

import random

ASPECTS = {
    "teaching": {
        "heading": "Teaching Quality",
        "key": {
            "pos": ["Most students feel that the teaching quality is good and the concepts are explained clearly.",
                    "The teaching quality in most courses is excellent and the lectures are well organised.",
                    "Students are happy with the teaching quality because faculty explain concepts with clear examples."],
            "neg": ["Many students feel that the teaching quality is poor and the concepts are not explained clearly.",
                    "The teaching quality in several courses is weak and the lectures are often rushed.",
                    "Students are unhappy with the teaching because classes focus only on reading the slides."],
            "mixed": ["The teaching quality is generally good, but some lectures are rushed at the end of the semester.",
                      "Students find the concepts well explained, although the pace of some lectures is too fast.",
                      "Most students rate the teaching quality as good, but they feel that a few lectures are rushed."],
        },
        "summary": {"pos": "teaching quality is good and concepts are explained clearly .",
                    "neg": "teaching quality is poor and lectures are rushed .",
                    "mixed": "teaching quality is good but some lectures are rushed ."},
        "detail": {"pos": ["Faculty members use real-world examples in class.",
                           "Difficult subjects like operating systems become easier to follow.",
                           "Assignments are closely related to what is taught in class.",
                           "Tutorial sessions are conducted before every examination."],
                   "neg": ["Some lectures finish without covering the full syllabus.",
                           "Students asked for more tutorial sessions before the examinations.",
                           "A few teachers read directly from the slides.",
                           "Several classes were cancelled without prior notice."]},
    },
    "infrastructure": {
        "heading": "Infrastructure",
        "key": {
            "pos": ["The campus infrastructure is good and the classrooms are spacious and well maintained.",
                    "Students appreciate the infrastructure, especially the new smart boards and comfortable classrooms."],
            "neg": ["The infrastructure needs improvement because the Wi-Fi connectivity on campus is poor.",
                    "Students complained that the internet connection in the hostels and library is unreliable.",
                    "The classrooms are overcrowded and the air conditioning often does not work."],
            "mixed": ["The classrooms are spacious, but the Wi-Fi connectivity in the hostels and library is poor.",
                      "Students like the new smart boards, although the internet connection frequently disconnects.",
                      "The infrastructure is mostly good, but the Wi-Fi in the hostels is slow and unreliable."],
        },
        "summary": {"pos": "infrastructure is good and classrooms are well maintained .",
                    "neg": "infrastructure is poor and wi-fi connectivity is unreliable .",
                    "mixed": "classrooms are good but wi-fi connectivity is poor ."},
        "detail": {"pos": ["The cafeteria was renovated and the seating space is adequate.",
                           "Drinking water and clean washrooms are available in every block.",
                           "The auditorium was upgraded with a new sound system."],
                   "neg": ["The Wi-Fi frequently disconnects during peak hours.",
                           "The air conditioning in some blocks does not work in summer.",
                           "Students reported that the lifts are often out of service.",
                           "Parking space near the academic block is insufficient."]},
    },
    "lab": {
        "heading": "Laboratory Facilities",
        "key": {
            "pos": ["The laboratory facilities are excellent and every student gets a working system.",
                    "Students are satisfied with the labs because the equipment is modern and well maintained."],
            "neg": ["The laboratory facilities need significant improvement because many computers are outdated.",
                    "Students reported that the lab equipment is old and the number of working systems is not sufficient.",
                    "Many lab computers are slow and the required software is not installed."],
            "mixed": ["The lab assistants are helpful, but many computers in the labs are outdated.",
                      "The laboratory staff are supportive, although the lab equipment is old."],
        },
        "summary": {"pos": "laboratory facilities are good and the equipment is modern .",
                    "neg": "laboratory facilities need improvement because computers are outdated .",
                    "mixed": "lab staff are helpful but many computers are outdated ."},
        "detail": {"pos": ["Licensed software is installed on all lab systems.",
                           "Lab manuals are provided at the start of the semester.",
                           "Lab hours are extended during project reviews."],
                   "neg": ["Some computers take a long time to boot.",
                           "Licensed software is not installed on all systems.",
                           "Students suggested extending the lab hours till 8 PM.",
                           "Large batches have to share a few working systems."]},
    },
    "faculty": {
        "heading": "Faculty Interaction",
        "key": {
            "pos": ["Faculty members are approachable and willing to clear doubts after class.",
                    "Students feel that faculty interaction is very good and the mentors are supportive."],
            "neg": ["Students feel that faculty members are not approachable outside the classroom.",
                    "Faculty interaction is limited and doubts are rarely cleared after class."],
            "mixed": ["Faculty members are approachable, but responses to emails are sometimes slow.",
                      "Students find the mentors supportive, although faculty are hard to reach during examinations."],
        },
        "summary": {"pos": "faculty members are approachable and supportive .",
                    "neg": "faculty members are not approachable and interaction is limited .",
                    "mixed": "faculty members are approachable but email responses are slow ."},
        "detail": {"pos": ["Mentoring sessions are conducted every month.",
                           "Students feel comfortable discussing career concerns with their mentors.",
                           "Faculty share additional reading material on the learning portal."],
                   "neg": ["Responses to emails are slow during the examination period.",
                           "Office hours are not followed regularly.",
                           "Some students hesitate to ask questions in class."]},
    },
    "satisfaction": {
        "heading": "Student Satisfaction",
        "key": {
            "pos": ["Overall student satisfaction is high and most students would recommend the programme.",
                    "Most students are satisfied with their overall experience in the department."],
            "neg": ["Overall student satisfaction is low and many students are disappointed with the facilities.",
                    "Many students are dissatisfied with their overall experience in the department."],
            "mixed": ["Overall student satisfaction is moderately high, but some students are unhappy with the facilities.",
                      "Most students are satisfied overall, although outdated labs and poor internet remain concerns."],
        },
        "summary": {"pos": "overall student satisfaction is high .",
                    "neg": "overall student satisfaction is low .",
                    "mixed": "overall student satisfaction is moderately high despite some concerns ."},
        "detail": {"pos": ["Students are satisfied with the curriculum and placement support.",
                           "Most students rated their experience as good or excellent.",
                           "Many students would recommend the programme to their juniors."],
                   "neg": ["The main reasons for dissatisfaction are outdated labs and poor internet.",
                           "Several students said the fees are too high for the facilities provided.",
                           "Some students are considering transferring to other colleges."]},
    },
}

FILLERS = ["A few respondents left this section blank.",
           "Responses were collected through an online form.",
           "Some comments were repeated by several students.",
           "The responses were similar across all years of study.",
           "This section received a large number of comments."]


def make_paragraph(aspect, polarity, rng):
    a = ASPECTS[aspect]
    key = rng.choice(a["key"][polarity])
    if polarity == "mixed":
        details = rng.sample(a["detail"]["pos"], 1) + rng.sample(a["detail"]["neg"], rng.randint(1, 2))
    else:
        pool = a["detail"]["pos" if polarity == "pos" else "neg"]
        details = rng.sample(pool, min(len(pool), rng.randint(2, 3)))
    if rng.random() < 0.3:
        details.append(rng.choice(FILLERS))
    rng.shuffle(details)
    pos = 0 if rng.random() < 0.7 else rng.randint(1, len(details))
    sentences = details[:pos] + [key] + details[pos:]
    labels = [int(i == pos) for i in range(len(sentences))]
    return {"aspect": aspect, "heading": a["heading"], "sentences": sentences, "labels": labels,
            "summary": a["summary"][polarity]}


def generate_documents(n_docs=400, seed=0):
    rng = random.Random(seed)
    docs = []
    for _ in range(n_docs):
        aspects = rng.sample(list(ASPECTS), rng.randint(3, 5))
        docs.append([make_paragraph(a, rng.choice(["pos", "neg", "mixed"]), rng) for a in aspects])
    return docs
